# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file 'cwin_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
is_off = False

class ChatWin(QtWidgets.QMainWindow):

    def closeEvent(self, event):
        is_off = True
        event.accept()
    def setupUi(self, Chat):
        Chat.setObjectName("Chat")
        Chat.resize(550, 500)
        Chat.setStyleSheet("\n"
                           "")
        self.centralwidget = QtWidgets.QWidget(Chat)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(80, 340, 391, 51))
        self.lineEdit.setStyleSheet("background-color: #3f3f3f;\n"
                                    "border: 2px solid #2d2d2d;\n"
                                    "border-radius: 5px;\n"
                                    "color: #909090;")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 400, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: #3f3 f3f;\n"
                                      "border: 2px solid #2d2d2d;\n"
                                      "border-radius: 5px;\n"
                                      "color: #c4c4c4;")
        self.pushButton.setObjectName("pushButton")
        self.connect = QtWidgets.QPushButton(self.centralwidget)
        self.connect.setGeometry(QtCore.QRect(280, 400, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.connect.setFont(font)
        self.connect.setStyleSheet("background-color: #3f3 f3f;\n"
                                   "border: 2px solid #2d2d2d;\n"
                                   "border-radius: 5px;\n"
                                   "color: #c4c4c4;")
        self.connect.setObjectName("connect")
        self.clear_chat = QtWidgets.QPushButton(self.centralwidget)
        self.clear_chat.setGeometry(QtCore.QRect(80, 450, 391, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.clear_chat.setFont(font)
        self.clear_chat.setStyleSheet("background-color: #3f3 f3f;\n"
                                      "border: 2px solid #2d2d2d;\n"
                                      "border-radius: 5px;\n"
                                      "color: #c4c4c4;")
        self.clear_chat.setObjectName("clear_chat")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(33, 50, 497, 281))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setStyleSheet("background-color: #3f3f3f;\n"
                                         "border: 2px solid #2d2d2d;\n"
                                         "color: white;")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(26, 43, 511, 461))
        self.label.setStyleSheet("background-color: #4d4d4d;\n"
                                 "border: 2px solid #2d2d2d;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.Chat_Window = QtWidgets.QPushButton(self.centralwidget)
        self.Chat_Window.setGeometry(QtCore.QRect(26, 20, 63, 23))
        self.Chat_Window.setStyleSheet("border: 2px solid #2d2d2d;\n"
                                       "border-bottom: 0px solid #2d2d2d;\n"
                                       "border-top-left-radius: 10px;\n"
                                       "background-color: #4d4d4d;")
        self.Chat_Window.setObjectName("Chat_Window")
        self.Settings_window = QtWidgets.QPushButton(self.centralwidget)
        self.Settings_window.setGeometry(QtCore.QRect(86, 20, 71, 21))
        self.Settings_window.setStyleSheet("border: 2px solid #2d2d2d;\n"
                                           "border-bottom: 0px solid #2d2d2d;")
        self.Settings_window.setObjectName("Settings_window")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-4, -8, 561, 511))
        self.label_2.setStyleSheet("background-color: #3d3d3d;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.label.raise_()
        self.lineEdit.raise_()
        self.pushButton.raise_()
        self.connect.raise_()
        self.clear_chat.raise_()
        self.plainTextEdit.raise_()
        self.Chat_Window.raise_()
        self.Settings_window.raise_()
        Chat.setCentralWidget(self.centralwidget)

        self.retranslateUi(Chat)
        QtCore.QMetaObject.connectSlotsByName(Chat)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setText(_translate("MainWindow", "Текстовое сообщение..."))
        self.pushButton.setText(_translate("MainWindow", "Отправить"))
        self.connect.setText(_translate("MainWindow", "Подключится"))
        self.clear_chat.setText(_translate("MainWindow", "Очистить"))
        self.Chat_Window.setText(_translate("MainWindow", "Чат"))
        self.Settings_window.setText(_translate("MainWindow", "Настройки"))


    def viuve(self, data):
        self.plainTextEdit.appendPlainText(data)


